# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('www', models.URLField()),
                ('slug', models.SlugField(max_length=300)),
                ('timestamps', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
