# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0002_auto_20180206_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
