# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_auto_20180206_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
